# Generated by Django 5.1.6 on 2026-04-07 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220114_1429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('is_admin_reply', models.BooleanField(default=False, verbose_name='Admin trả lời?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhắn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Tin nhắn hỗ trợ',
                'verbose_name_plural': 'Tin nhắn hỗ trợ',
                'ordering': ['created_at'],
            },
        ),
    ]
