# Generated by Django 5.1.6 on 2026-04-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_voucher_target_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='target_user',
        ),
    ]
