# Generated by Django 5.1.6 on 2026-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_voucher_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD - Thanh toán khi nhận hàng'), ('paypal', 'PayPal'), ('momo', 'MoMo'), ('vnpay', 'VNPay')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
