# Generated by Django 5.1.6 on 2026-05-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Thống kê nguồn tiền',
                'verbose_name_plural': '📊 Thống kê nguồn tiền',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
    ]
